In [1]:
# Import Python packages
import pandas as pd
import numpy as np
import biom
from biom import Table
from biom.util import biom_open
from biom import load_table
import h5py

In [2]:
def load_biom_table(biom_path):
    # Load BIOM table and convert to a DataFrame
    table = biom.load_table(biom_path)
    df = pd.DataFrame(table.matrix_data.toarray(),
                      index=table.ids(axis='observation'),
                      columns=table.ids(axis='sample'))

    
    return df

In [3]:
def df_to_biom(df, out_biom_path):
    table = Table(
        df.values,
        observation_ids=df.index.astype(str).tolist(),
        sample_ids=df.columns.astype(str).tolist()
    )

    with h5py.File(out_biom_path, "w") as h5f:
        table.to_hdf5(
            h5f,
            generated_by="column intersection filter"
        )

In [4]:
# Load tables
path_16S_V1V3 = "../from_Qiita/179426_feature-table_16S_V1V3_rare-11054_sampleIDfixed.biom"
path_16S_V4 = "../from_Qiita/174951_feature-table_16S_V4_rare-3769_sampleIDfixed.biom"
path_metabolomics =  "../../../../Data/metabolomics/Run3_10252024/output/metabolomics_table_final_sampleIDfixed.biom"

df_16S_V1V3 = load_biom_table(path_16S_V1V3)
df_16S_V4 = load_biom_table(path_16S_V4)
df_metabolomics = load_biom_table(path_metabolomics)

In [5]:
# View V1-V3 table
df_16S_V1V3

,LAMI.RD001.D0.C1,LAMI.RD001.D0.C2,LAMI.RD001.D14.C1,LAMI.RD001.D28.C1,LAMI.RD002.D14.C1,LAMI.RD006.COSM1,LAMI.RD001.D28.C2,LAMI.RD007.D0.C1,LAMI.RD002.D14.C2,LAMI.RD011.D28.C1,...,LAMI.RD318.D28.C2,LAMI.RD319.D21.C1,LAMI.RD319.D28.C3,LAMI.RD319.D21.C2,LAMI.RD319.D7.C3,LAMI.RD318.D28.C3,LAMI.RD319.D14.C1,LAMI.RD319.D14.C2,LAMI.RD319.D9.C1,LAMI.RD319.D9.C2
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAAGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCCCTGCTTGCAGGGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTGATCTGCCCTGCACTTCGGGATAAGCTTGGGAAACTGGGTCTAATACCGGATAG,18.0,76.0,27.0,82.0,6.0,0.0,136.0,0.0,0.0,0.0,...,2.0,0.0,6.0,2.0,0.0,1.0,7.0,1.0,0.0,7.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTTCTCCGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,93.0,138.0,49.0,0.0,2.0,0.0,55.0,7.0,0.0,2.0,...,0.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGAAGTTTTTCTGGTGCTTGCACTAGAAAAACTTAGCGGCGAACGGGTGAGTAACACGTAAAGAACCTGCCTCATAGACTGGGACAACTATTGGAAACGATAGCTAATACC,66.0,24.0,41.0,46.0,0.0,0.0,36.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCTCCAGCTTGCTGGAGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTAATCTGCCCTGCACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGGAT,241.0,391.0,729.0,601.0,135.0,0.0,1168.0,17.0,90.0,151.0,...,8.0,42.0,88.0,58.0,17.0,8.0,25.0,69.0,103.0,82.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTCTTCTGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,254.0,325.0,41.0,150.0,53.0,0.0,61.0,18.0,64.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGCTGAAGCTTGGTGCTTGCACTGGGTGGATGAGTGGCGAACGGGTGAGTAATACGTGAGTAACCTGCCCTTGACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGG,0.0,30.0,0.0,21.0,1.0,0.0,18.0,0.0,29.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAGGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,41.0,...,2619.0,2895.0,4847.0,3136.0,7981.0,1604.0,4154.0,4016.0,5902.0,4075.0
ATTGAACGCTGGCGGCAGGCTTAACACATGCAAGTCGAACGGTAGCAGGAGAAAGCTTGCTTTCTTGCTGACGAGTGGCGGACGGGTGAGTAATGCTTGGGAATCTGGCTTATGGAGGGGGATAACTACGGGAAACTGTAGCTAATACCG,44.0,60.0,24.0,30.0,0.0,0.0,10.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCCTTACACATGCAAGTCGAACGGTAACAGGTCTTCGGATGCTGACGAGTGGCGAACGGGTGAGTAATACATCGGAACGTGCCCAGTAATGGGGGATAGCTCGGCGAAAGCCGGATTAATACCGCATACGCC,16.0,21.0,4.0,1.0,21.0,0.0,0.0,2.0,40.0,7.0,...,0.0,1.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# View V4 table
df_16S_V4

,LAMI.RD001.D0.C1,BLANK.LOREAL.2.2H,LAMI.RD001.D14.C1,LAMI.RD004.D0.C2,LAMI.RD001.D0.C2,LAMI.RD004.D28.C1,LAMI.RD011.D0.C2,LAMI.RD001.D14.C2,LAMI.RD004.D28.C2,LAMI.RD017.D14.C2,...,LAMI.RD319.D16.C1,LAMI.RD318.D16.C1,LAMI.RD319.D25.C2,LAMI.RD318.D18.C1,LAMI.RD318.D4.C2,LAMI.RD319.D16.C2,LAMI.RD319.D28.C1,LAMI.RD318.D9.C2,LAMI.RD319.D28.C2,LAMI.RD319.D2.C1
TACGTAGGGTGCGAGCGTTATCCGGAATTATTGGGCGTAAAGAGCTCGTAGGCGGTTTGTCGCGTCTGCCGTGAAAGTCCGGGGCTTAACTCCGGATCTGCGGTGGGTACGGGCAGACTAGAGTGCAGTAGGGGAGACTGGAATTCCTGG,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGGAGCTAGCGTTGTTCGGAATTACTGGGCGTAAAGCGCGCGTAGGCGGTCTTTTAAGTCAGAGGTGAAAGCCCGGGGCTCAACCCCGGAATAGCCTTTGAAACTGGAAGACTTGAATCTTGGAGAGGTCAGTGGAATTCCGAG,0.0,11.0,1.0,2.0,1.0,1.0,0.0,0.0,9.0,0.0,...,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0
TACGTAGGGTACTAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTCGTAGGTGGTTTGTCGCGTCTGCTGTGGAAACGTGCCGCTTAACGGTGCGCGTGCAGTGGGTACGGGCGGACTAGAGTGCAGTAGGGGAGTCTGGAATTCCTGG,11.0,0.0,123.0,0.0,4.0,5.0,0.0,50.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGCGCGCAGGTGGTTTCTTAAGTCTGATGTGAAATCTCGCGGCTCAACCGCGAGCGGTCATTGGAAACTGGGGAACTTGAGTGCAGAAGAGGATAGTGGAATTCCAAG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGAAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTCGTTAAGTTGGATGTGAAAGCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTGGCGAGCTAGAGTATGGCAGAGGGTGGTGGAATTTCCTG,0.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TACGTAGGGTGCAAGCGTTGTCCGGAATTACTGGGCGTAAAGAGCTCGTAGGTGGTTTGTCACGTCGTCTGTGAAATTCCACAGCTTAACTGTGGGCGTGCAGGCGATACGGGCTGACTTGAGTACTGTAGGGGTAACTGGAATTCCTGG,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACAGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTTGTTAAGTTGGATGTGAAAGCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTGGCAAGCTAGAGTACGGTAGAGGGTGGTGGAATTTCCTG,9.0,0.0,11.0,24.0,0.0,2.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTCAATTAAGTCTGATGTGAAAGCCCCCGGCTCAACCGGGGAGGGTCATTGGAAACTGGTTGACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATG,19.0,0.0,9.0,0.0,14.0,50.0,54.0,30.0,70.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTTAAGTCAGATGTGAAATCCCCGGGCTTAACCTGGGAACTGCATTTGAAACTGGCAGGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGG,0.0,0.0,0.0,19.0,0.0,51.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACAGAGGGTGCGAGCGTTAATCGGATTTACTGGGCGTAAAGCGTGCGTAGGCGGCTTATTAAGTCGGATGTGAAATCCCCGAGCTTAACTTGGGAATTGCATTCGATACTGGTGAGCTAGAGTATGGGAGAGGATGGTAGAATTCCAGG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# View metabolomics table
df_metabolomics

,LAMI.RD319.D9.C2,LAMI.RD317.D16.C2,LAMI.RD319.D2.C1,LAMI.RD011.D28.C1,LAMI.RD014.D0.C1,LAMI.RD319.D2.C3,LAMI.RD317.D14.C1,LAMI.RD318.D21.C2,LAMI.RD319.D16.C1,LAMI.RD318.D0.C1,...,LAMI.RD310.D14.C1,LAMI.RD007.D0.C1,LAMI.RD306.D14.C3,LAMI.RD310.D16.C2,LAMI.RD001.D14.C2,LAMI.RD308.D23.C1,LAMI.RD304.D9.C1,LAMI.RD310.D7.C3,LAMI.RD306.D11.C2,LAMI.RD313.D9.C2
17896,44480.562,55293.973,10102.257,47160.402,15450.1170,12816.9260,12468.242,17850.795,18974.502,13629.175,...,1661.3948,1770.395,1880.5396,2468.2737,1691.8174,4123.7773,2046.6823,1118.7435,2270.8936,2274.2695
5240,125222.450,184299.860,89956.130,121793.330,212080.7000,124541.9500,170269.520,184158.600,116874.160,11403.561,...,2572.3590,9023.507,3359.1345,3659.3733,2993.7908,1553.3168,9267.2340,9260.1390,1222.1909,1703.3276
31854,0.000,0.000,0.000,0.000,6042.1406,4383.3687,0.000,0.000,0.000,0.000,...,8092.6270,6325.817,60928.7770,6757.6772,18713.6840,55235.3050,4988.3047,6524.1807,69714.9300,40012.9060
31138,0.000,0.000,0.000,0.000,0.0000,0.0000,0.000,0.000,0.000,0.000,...,2527.2710,26288.047,64151.6200,13210.0700,26825.9730,242216.3800,4131.1924,117053.9140,96446.8900,79258.3750
30442,0.000,0.000,0.000,0.000,0.0000,0.0000,0.000,0.000,0.000,0.000,...,16884.0550,26894.043,67715.9840,10375.5290,19810.8700,32245.6230,16856.2290,24450.9980,39925.5270,34121.1520
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36120,0.000,0.000,0.000,0.000,0.0000,0.0000,0.000,0.000,0.000,0.000,...,0.0000,0.000,0.0000,0.0000,0.0000,9654.5940,0.0000,0.0000,0.0000,0.0000
34141,0.000,0.000,0.000,0.000,0.0000,0.0000,0.000,0.000,0.000,0.000,...,0.0000,0.000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
34312,0.000,0.000,0.000,0.000,0.0000,0.0000,0.000,0.000,0.000,0.000,...,0.0000,0.000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
29373,0.000,0.000,0.000,0.000,14144.1520,0.0000,0.000,0.000,0.000,0.000,...,0.0000,0.000,17800.4260,0.0000,0.0000,0.0000,0.0000,15128.1290,17349.2230,0.0000
29327,0.000,0.000,0.000,0.000,8448.2920,0.0000,0.000,0.000,0.000,0.000,...,0.0000,0.000,10025.9750,0.0000,0.0000,0.0000,0.0000,10580.1480,9177.5240,0.0000

In [8]:
# Get shared sample IDs across all datasets
shared_samples = (
    set(df_16S_V1V3.columns)
    & set(df_16S_V4.columns)
    & set(df_metabolomics.columns)
)

shared_samples = sorted(shared_samples)

print(f"Number of shared samples: {len(shared_samples)}")

Number of shared samples: 184

In [9]:
# Filter tables to same intersecton of shared samples
df_16S_V1V3_filt = df_16S_V1V3.loc[:, shared_samples]
df_16S_V4_filt = df_16S_V4.loc[:, shared_samples]
df_metab_filt = df_metabolomics.loc[:, shared_samples]

In [10]:
df_to_biom(
    df_16S_V1V3_filt,
    "179426_feature-table_16S_V1V3_rare-11054_sampleIDfixed_16S-metaB-aligned.biom"
)

df_to_biom(
    df_16S_V4_filt,
    "174951_feature-table_16S_V4_rare-3769_sampleIDfixed_16S-metaB-aligned.biom"
)

df_to_biom(
    df_metab_filt,
    "../../../../Data/metabolomics/Run3_10252024/output/metabolomics_table_final_sampleIDfixed_16S-metaB-aligned.biom"
)