In [1]:
# Import Python packages
import pandas as pd
import numpy as np
import biom
from biom import Table
from biom.util import biom_open
from biom import load_table
import h5py

In [2]:
def load_biom_table(biom_path):
    # Load BIOM table and convert to a DataFrame
    table = biom.load_table(biom_path)
    df = pd.DataFrame(table.matrix_data.toarray(),
                      index=table.ids(axis='observation'),
                      columns=table.ids(axis='sample'))

    
    return df

In [3]:
def df_to_biom(df, out_biom_path):
    table = Table(
        df.values,
        observation_ids=df.index.astype(str).tolist(),
        sample_ids=df.columns.astype(str).tolist()
    )

    with h5py.File(out_biom_path, "w") as h5f:
        table.to_hdf5(
            h5f,
            generated_by="column intersection filter"
        )

In [4]:
# Load tables
path_16S_V1V3 = "../from_Qiita/179426_feature-table_16S_V1V3_rare-11054_sampleIDfixed.biom"
path_16S_V4 = "../from_Qiita/174951_feature-table_16S_V4_rare-3769_sampleIDfixed.biom"
# path_metabolomics =  "../../../../Data/metabolomics/Run3_10252024/output/metabolomics_table_final_sampleIDfixed.biom"
path_metabolomics = '../../../../Data/metabolomics/Run3_10252024/metabolomics_method2.biom'

df_16S_V1V3 = load_biom_table(path_16S_V1V3)
df_16S_V4 = load_biom_table(path_16S_V4)
df_metabolomics = load_biom_table(path_metabolomics)

In [5]:
# View V1-V3 table
df_16S_V1V3

,LAMI.RD001.D0.C1,LAMI.RD001.D0.C2,LAMI.RD001.D14.C1,LAMI.RD001.D28.C1,LAMI.RD002.D14.C1,LAMI.RD006.COSM1,LAMI.RD001.D28.C2,LAMI.RD007.D0.C1,LAMI.RD002.D14.C2,LAMI.RD011.D28.C1,...,LAMI.RD318.D28.C2,LAMI.RD319.D21.C1,LAMI.RD319.D28.C3,LAMI.RD319.D21.C2,LAMI.RD319.D7.C3,LAMI.RD318.D28.C3,LAMI.RD319.D14.C1,LAMI.RD319.D14.C2,LAMI.RD319.D9.C1,LAMI.RD319.D9.C2
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAAGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCCCTGCTTGCAGGGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTGATCTGCCCTGCACTTCGGGATAAGCTTGGGAAACTGGGTCTAATACCGGATAG,18.0,76.0,27.0,82.0,6.0,0.0,136.0,0.0,0.0,0.0,...,2.0,0.0,6.0,2.0,0.0,1.0,7.0,1.0,0.0,7.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTTCTCCGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,93.0,138.0,49.0,0.0,2.0,0.0,55.0,7.0,0.0,2.0,...,0.0,1.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTCGAGCGAAGTTTTTCTGGTGCTTGCACTAGAAAAACTTAGCGGCGAACGGGTGAGTAACACGTAAAGAACCTGCCTCATAGACTGGGACAACTATTGGAAACGATAGCTAATACC,66.0,24.0,41.0,46.0,0.0,0.0,36.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGGAAAGGCTCCAGCTTGCTGGAGTACTCGAGTGGCGAACGGGTGAGTAACACGTGGGTAATCTGCCCTGCACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGGAT,241.0,391.0,729.0,601.0,135.0,0.0,1168.0,17.0,90.0,151.0,...,8.0,42.0,88.0,58.0,17.0,8.0,25.0,69.0,103.0,82.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GACGAACGCTGGCGGCGTGCCTAATACATGCAAGTAGAACGCTGAAGGAGGAGCTTGCTCTTCTGGATGAGTTGCGAACGGGTGAGTAACGCGTAGGTAACCTGCCTGGTAGCGGGGGATAACTATTGGAAACGATAGCTAATACCGCAT,254.0,325.0,41.0,150.0,53.0,0.0,61.0,18.0,64.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GACGAACGCTGGCGGCGTGCTTAACACATGCAAGTCGAACGCTGAAGCTTGGTGCTTGCACTGGGTGGATGAGTGGCGAACGGGTGAGTAATACGTGAGTAACCTGCCCTTGACTCTGGGATAAGCCTGGGAAACTGGGTCTAATACTGG,0.0,30.0,0.0,21.0,1.0,0.0,18.0,0.0,29.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCTTTACACATGCAAGTCGAACGGCAGCGAGGAGAAGCTTGCTTCTCTGTCGGCGAGTGGCGAACGGGTGAGTATAGCATCGGAACGTGCCAAGTAGTGGGGGATAACCAAACGAAAGTTTGGCTAATACCG,0.0,0.0,0.0,3.0,0.0,0.0,0.0,4.0,0.0,41.0,...,2619.0,2895.0,4847.0,3136.0,7981.0,1604.0,4154.0,4016.0,5902.0,4075.0
ATTGAACGCTGGCGGCAGGCTTAACACATGCAAGTCGAACGGTAGCAGGAGAAAGCTTGCTTTCTTGCTGACGAGTGGCGGACGGGTGAGTAATGCTTGGGAATCTGGCTTATGGAGGGGGATAACTACGGGAAACTGTAGCTAATACCG,44.0,60.0,24.0,30.0,0.0,0.0,10.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ATTGAACGCTGGCGGCATGCCTTACACATGCAAGTCGAACGGTAACAGGTCTTCGGATGCTGACGAGTGGCGAACGGGTGAGTAATACATCGGAACGTGCCCAGTAATGGGGGATAGCTCGGCGAAAGCCGGATTAATACCGCATACGCC,16.0,21.0,4.0,1.0,21.0,0.0,0.0,2.0,40.0,7.0,...,0.0,1.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# View V4 table
df_16S_V4

,LAMI.RD001.D0.C1,LAMI.RD001.D14.C1,LAMI.RD004.D0.C2,LAMI.RD001.D0.C2,LAMI.RD004.D28.C1,LAMI.RD011.D0.C2,LAMI.RD001.D14.C2,LAMI.RD004.D28.C2,LAMI.RD017.D14.C2,LAMI.RD011.D14.C1,...,LAMI.RD319.D16.C1,LAMI.RD318.D16.C1,LAMI.RD319.D25.C2,LAMI.RD318.D18.C1,LAMI.RD318.D4.C2,LAMI.RD319.D16.C2,LAMI.RD319.D28.C1,LAMI.RD318.D9.C2,LAMI.RD319.D28.C2,LAMI.RD319.D2.C1
TACGTAGGGTGCGAGCGTTATCCGGAATTATTGGGCGTAAAGAGCTCGTAGGCGGTTTGTCGCGTCTGCCGTGAAAGTCCGGGGCTTAACTCCGGATCTGCGGTGGGTACGGGCAGACTAGAGTGCAGTAGGGGAGACTGGAATTCCTGG,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGGAGCTAGCGTTGTTCGGAATTACTGGGCGTAAAGCGCGCGTAGGCGGTCTTTTAAGTCAGAGGTGAAAGCCCGGGGCTCAACCCCGGAATAGCCTTTGAAACTGGAAGACTTGAATCTTGGAGAGGTCAGTGGAATTCCGAG,0.0,1.0,2.0,1.0,1.0,0.0,0.0,9.0,0.0,0.0,...,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0
TACGTAGGGTACTAGCGTTGTCCGGAATTATTGGGCGTAAAGAGCTCGTAGGTGGTTTGTCGCGTCTGCTGTGGAAACGTGCCGCTTAACGGTGCGCGTGCAGTGGGTACGGGCGGACTAGAGTGCAGTAGGGGAGTCTGGAATTCCTGG,11.0,123.0,0.0,4.0,5.0,0.0,50.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGCGCGCAGGTGGTTTCTTAAGTCTGATGTGAAATCTCGCGGCTCAACCGCGAGCGGTCATTGGAAACTGGGGAACTTGAGTGCAGAAGAGGATAGTGGAATTCCAAG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGAAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTCGTTAAGTTGGATGTGAAAGCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTGGCGAGCTAGAGTATGGCAGAGGGTGGTGGAATTTCCTG,0.0,0.0,0.0,0.0,14.0,0.0,0.0,2.0,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TACGTAGGGTGCAAGCGTTGTCCGGAATTACTGGGCGTAAAGAGCTCGTAGGTGGTTTGTCACGTCGTCTGTGAAATTCCACAGCTTAACTGTGGGCGTGCAGGCGATACGGGCTGACTTGAGTACTGTAGGGGTAACTGGAATTCCTGG,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACAGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCGCGTAGGTGGTTTGTTAAGTTGGATGTGAAAGCCCCGGGCTCAACCTGGGAACTGCATCCAAAACTGGCAAGCTAGAGTACGGTAGAGGGTGGTGGAATTTCCTG,9.0,11.0,24.0,0.0,2.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
TACGTAGGTGGCAAGCGTTGTCCGGATTTATTGGGCGTAAAGCGAGCGCAGGCGGTCAATTAAGTCTGATGTGAAAGCCCCCGGCTCAACCGGGGAGGGTCATTGGAAACTGGTTGACTTGAGTGCAGAAGAGGAGAGTGGAATTCCATG,19.0,9.0,0.0,14.0,50.0,54.0,30.0,70.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTCTGTTAAGTCAGATGTGAAATCCCCGGGCTTAACCTGGGAACTGCATTTGAAACTGGCAGGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGG,0.0,0.0,19.0,0.0,51.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
TACAGAGGGTGCGAGCGTTAATCGGATTTACTGGGCGTAAAGCGTGCGTAGGCGGCTTATTAAGTCGGATGTGAAATCCCCGAGCTTAACTTGGGAATTGCATTCGATACTGGTGAGCTAGAGTATGGGAGAGGATGGTAGAATTCCAGG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0

In [7]:
# View metabolomics table
df_metabolomics

,LAMI.RD001.D0.C1,LAMI.RD308.D2.C2,LAMI.RD304.D11.C1,LAMI.RD304.D11.C2,LAMI.RD304.D0.C1,LAMI.RD304.D0.C2,LAMI.RD001.D14.C1,LAMI.RD304.D0.C3,LAMI.RD001.D14.C2,LAMI.RD006.D0.C1,...,LAMI.RD310.D0.C2,LAMI.RD310.D0.C3,LAMI.RD304.D9.C1,LAMI.RD304.D9.C2,LAMI.RD319.D2.C1,LAMI.RD318.D9.C3,LAMI.RD308.D9.C3,LAMI.RD319.D2.C2,LAMI.RD319.D2.C3,LAMI.RD318.D21.C2
4293,4.770763e+03,4166.871,2342.999,740.01514,725.83435,5084.213,6102.134,0.000,15477.288,5.137698e+03,...,4188.890,3274.6375,2352.2485,5466.2266,0.000,0.000,0.000,1567.8933,0.0000,0.000
15974,0.000000e+00,0.000,0.000,6008.39450,6228.51170,0.000,0.000,0.000,0.000,0.000000e+00,...,17157.180,8754.7850,0.0000,0.0000,0.000,0.000,0.000,0.0000,25945.3710,0.000
2531,7.281270e+04,56668.180,116903.530,69846.52000,75098.50000,178867.020,141313.830,76078.484,137003.560,1.089918e+05,...,56698.500,83862.3900,76001.6000,91359.5700,45993.550,53799.130,30274.117,63744.7970,47938.9100,23423.326
5907,1.022406e+06,322180.030,548906.900,303948.28000,438357.53000,846918.100,644094.440,491530.900,4245851.500,1.708089e+06,...,323473.700,491144.6000,319621.0300,427207.2800,227666.620,458503.400,1192993.400,458884.6200,403263.2800,415341.060
5946,0.000000e+00,0.000,0.000,0.00000,0.00000,0.000,0.000,0.000,24181.441,0.000000e+00,...,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.0000,0.0000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25998,9.886966e+04,366275.560,106990.060,55033.45300,107743.01000,174531.400,87759.940,80892.890,96833.766,8.546535e+04,...,51995.960,210237.8100,160127.3600,28965.0430,43539.740,40761.030,14812.991,100497.2340,13816.3010,82057.580
33060,0.000000e+00,0.000,0.000,1521.32070,0.00000,0.000,0.000,0.000,0.000,0.000000e+00,...,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.0000,9280.9160,0.000
30635,0.000000e+00,0.000,0.000,0.00000,0.00000,0.000,0.000,0.000,0.000,0.000000e+00,...,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.0000,1639.8352,0.000
26562,4.466812e+04,110988.580,66076.950,19372.97700,49133.24000,95173.340,104116.695,38695.656,90356.070,4.329559e+04,...,61393.040,60102.6880,58727.3900,123312.5800,50667.290,15749.498,0.000,0.0000,0.0000,32831.992
28336,8.376185e+03,11684.108,8903.791,8350.32900,10825.29500,7471.549,22818.605,8212.777,19060.340,4.456192e+03,...,16916.867,18855.3630,10425.5200,25366.2090,16235.378,5134.834,0.000,2682.9302,5966.7130,11968.683

In [8]:
# Get shared sample IDs across all datasets
shared_samples = (
    set(df_16S_V1V3.columns)
    & set(df_16S_V4.columns)
    & set(df_metabolomics.columns)
)

shared_samples = sorted(shared_samples)

print(f"Number of shared samples: {len(shared_samples)}")

Number of shared samples: 143

In [9]:
# Filter tables to same intersecton of shared samples
df_16S_V1V3_filt = df_16S_V1V3.loc[:, shared_samples]
df_16S_V4_filt = df_16S_V4.loc[:, shared_samples]
df_metab_filt = df_metabolomics.loc[:, shared_samples]

In [ ]:
df_to_biom(
    df_16S_V1V3_filt,
    "179426_feature-table_16S_V1V3_rare-11054_sampleIDfixed_16S-metaB-aligned.biom"
)

df_to_biom(
    df_16S_V4_filt,
    "174951_feature-table_16S_V4_rare-3769_sampleIDfixed_16S-metaB-aligned.biom"
)

df_to_biom(
    df_metab_filt,
    "../../../../Data/metabolomics/Run3_10252024/metabolomics_method2_16S-metaB-aligned.biom"
)