# Check of sample numbers of individual numbers
## Supposed to be 16 acne, and 15 healthy collected, but 10 of each used for analyses

In [18]:
import pandas as pd
import biom
from biom import load_table

In [19]:
# Load metadata
metadata_path = '../Metadata/metadata_final_22102024.tsv'  # Replace with your actual path

metadata = pd.read_csv(metadata_path, sep='\t')
metadata = metadata.set_index('SampleID')

metadata['cohort'].value_counts()

cohort
acne       209
control     57
Name: count, dtype: int64

In [20]:
# Replace with the actual column name used for grouping (e.g., 'skin_status')
group_col = 'cohort'  

# Replace with your actual subject ID column
if 'subject_ID' in metadata.columns:
    id_col = 'subject_ID'
elif 'host_subject_ID' in metadata.columns:
    id_col = 'host_subject_ID'
else:
    raise ValueError("No subject ID column found in metadata.")

# Count unique individuals in each group
group_counts = metadata.groupby(group_col)[id_col].nunique()

# Print the counts
print("Number of unique individuals per group:")
for group, count in group_counts.items():
    print(f"{group}: {count} individuals")

Number of unique individuals per group:
acne: 10 individuals
control: 10 individuals

In [21]:
metadata['group'].value_counts()

group
Acne_L     159
Healthy     57
Acne_NL     50
Name: count, dtype: int64

In [22]:
metab_df = pd.read_csv('../Data/metabolomics/Run3_10252024/Sequence_order_10262024.csv')

# Count samples starting with each number
number_counts = metab_df['File.Name'].str[0].value_counts().sort_index()
print("\nNumber of samples starting with each digit:")
print(number_counts)
# Calculate total samples
total_samples = number_counts.sum()
print(f"\nTotal number of samples: {total_samples}")
print(38 + 39 + 33 + 36 + 28 + 35 + 44)

Number of samples starting with each digit:
File.Name
1    38
2    39
3    33
4    36
5    28
6    35
7    44
8     5
9     2
P    30
Q    52
V    22
b     4
w     6
Name: count, dtype: int64

Total number of samples: 374
253

### Check sample numbers for 16S

In [23]:
# Function to load BIOM table, sort rows by sum
def biom_to_df(biom_path):

    # Load BIOM table and convert to a DataFrame
    table = biom.load_table(biom_path)

    df = pd.DataFrame(table.matrix_data.toarray(),
                      index=table.ids(axis='observation'),
                      columns=table.ids(axis='sample'))
    
    return df

In [27]:
V1V3_16S = biom_to_df('../Data/16S/Tables/16S_V4_Genus_uncollapsed_absolute.biom')
V1V3_16S

,LAMI.RD001.D0.C1,LAMI.RD001.D14.C1,LAMI.RD004.D0.C2,LAMI.RD001.D0.C2,LAMI.RD004.D28.C1,LAMI.RD011.D0.C2,LAMI.RD001.D14.C2,LAMI.RD004.D28.C2,LAMI.RD017.D14.C2,LAMI.RD011.D14.C1,...,LAMI.RD319.D16.C1,LAMI.RD318.D16.C1,LAMI.RD319.D25.C2,LAMI.RD318.D18.C1,LAMI.RD318.D4.C2,LAMI.RD319.D16.C2,LAMI.RD319.D28.C1,LAMI.RD318.D9.C2,LAMI.RD319.D28.C2,LAMI.RD319.D2.C1
d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Micrococcales; f__Micrococcaceae|ASV1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
d__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Sphingomonadales; f__Sphingomonadaceae; g__Sphingopyxis,0.0,1.0,2.0,1.0,1.0,0.0,0.0,9.0,0.0,0.0,...,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,0.0,1.0
d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Micrococcales; f__Brevibacteriaceae; g__Brevibacterium|ASV1,11.0,123.0,0.0,4.0,5.0,0.0,50.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
d__Bacteria; p__Firmicutes; c__Bacilli; o__Bacillales; f__Planococcaceae; g__Rummeliibacillus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Pseudomonadaceae; g__Pseudomonas|ASV1,0.0,0.0,0.0,0.0,14.0,0.0,0.0,2.0,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Corynebacteriales; f__Corynebacteriaceae; g__Corynebacterium|ASV21,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Pseudomonadaceae; g__Pseudomonas|ASV6,9.0,11.0,24.0,0.0,2.0,0.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
d__Bacteria; p__Firmicutes; c__Bacilli; o__Lactobacillales|ASV2,19.0,9.0,0.0,14.0,50.0,54.0,30.0,70.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Enterobacterales; f__Erwiniaceae; g__Pantoea,0.0,0.0,19.0,0.0,51.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Moraxellaceae; g__Acinetobacter|ASV9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0

In [28]:
V1V3_16S = biom_to_df('../Data/16S/Tables/16S_V4_Genus_collapsed_absolute.biom')
V1V3_16S

,LAMI.RD001.D0.C1,LAMI.RD001.D14.C1,LAMI.RD004.D0.C2,LAMI.RD001.D0.C2,LAMI.RD004.D28.C1,LAMI.RD011.D0.C2,LAMI.RD001.D14.C2,LAMI.RD004.D28.C2,LAMI.RD017.D14.C2,LAMI.RD011.D14.C1,...,LAMI.RD319.D16.C1,LAMI.RD318.D16.C1,LAMI.RD319.D25.C2,LAMI.RD318.D18.C1,LAMI.RD318.D4.C2,LAMI.RD319.D16.C2,LAMI.RD319.D28.C1,LAMI.RD318.D9.C2,LAMI.RD319.D28.C2,LAMI.RD319.D2.C1
g__Abiotrophia,14.0,21.0,0.0,9.0,0.0,0.0,30.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
g__Absconditabacteriales_(SR1),38.0,0.0,0.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
g__Acinetobacter,116.0,57.0,72.0,83.0,326.0,31.0,66.0,298.0,70.0,17.0,...,19.0,83.0,1.0,155.0,403.0,3.0,5.0,35.0,0.0,3.0
g__Actinomyces,19.0,48.0,2.0,10.0,6.0,5.0,25.0,3.0,11.0,3.0,...,1.0,4.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
g__Aerococcus,9.0,3.0,63.0,4.0,32.0,0.0,1.0,15.0,13.0,0.0,...,0.0,0.0,4.0,0.0,0.0,4.0,0.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
g__Veillonella,43.0,41.0,59.0,37.0,35.0,32.0,83.0,115.0,0.0,15.0,...,0.0,10.0,0.0,8.0,2.0,0.0,1.0,0.0,0.0,3.0
g__Vibrio,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
g__Weissella,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
g__Xanthomonas,0.0,1.0,0.0,0.0,1.0,0.0,8.0,0.0,0.0,2.0,...,1.0,1.0,2.0,21.0,1.0,0.0,0.0,0.0,1.0,0.0
g__uncultured,61.0,29.0,36.0,46.0,16.0,46.0,40.0,32.0,32.0,82.0,...,3562.0,3297.0,3599.0,3291.0,2595.0,3413.0,3525.0,3441.0,3627.0,3509.0