In [36]:
# Import Python packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import biom
from biom import load_table
from biom.util import biom_open
import numpy as np
from scipy.stats import mannwhitneyu
import matplotlib.ticker as ticker
from matplotlib.patches import Rectangle
from statsmodels.stats.multitest import multipletests
from matplotlib.colors import Normalize
from brokenaxes import brokenaxes
from matplotlib.colors import LinearSegmentedColormap

In [37]:
# Function to load BIOM table, sort rows by sum
def biom_to_df(biom_path):

    # Load BIOM table and convert to a DataFrame
    table = biom.load_table(biom_path)

    df = pd.DataFrame(table.matrix_data.toarray(),
                      index=table.ids(axis='observation'),
                      columns=table.ids(axis='sample'))
    
    
    # Sort rows by row sum in descending order
    df['row_sum'] = df.sum(axis=1)
    df = df.sort_values(by='row_sum', ascending=False)
    
    # Drop the 'row_sum' column before proceeding
    df = df.drop(columns=['row_sum'])

    # Transpose df
    df = df.T
    
    return df

In [38]:
# skin_group = "Acne_L"
# skin_group = "Acne_NL"
skin_group = "Healthy"

In [39]:
v4_asv_path = f'../Data/multi-omics/16S-ASV_V4-tbl_metaB-matched_relative_{skin_group}.biom'
biom_to_df(v4_asv_path)

,d__Bacteria; p__Firmicutes; c__Bacilli; o__Staphylococcales; f__Staphylococcaceae; g__Staphylococcus|ASV3,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Corynebacteriales; f__Corynebacteriaceae; g__Lawsonella,d__Bacteria; p__Firmicutes; c__Bacilli; o__Lactobacillales; f__Streptococcaceae; g__Streptococcus|ASV5,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Micrococcales; f__Micrococcaceae; g__Micrococcus|ASV1,d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales; f__Neisseriaceae; g__uncultured|ASV2,d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Burkholderiales; f__Neisseriaceae; g__uncultured|ASV3,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Corynebacteriales; f__Corynebacteriaceae; g__Corynebacterium|ASV15,d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pasteurellales; f__Pasteurellaceae; g__Haemophilus|ASV1,d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Moraxellaceae; g__Enhydrobacter,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Corynebacteriales; f__Corynebacteriaceae; g__Corynebacterium|ASV2,...,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Micrococcales; f__Micrococcaceae; g__Micrococcus|ASV2,d__Bacteria; p__Firmicutes; c__Clostridia; o__Peptostreptococcales-Tissierellales; f__Peptostreptococcales-Tissierellales; g__Anaerococcus|ASV5,d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Moraxellaceae; g__Acinetobacter|ASV2,d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Moraxellaceae; g__Moraxella|ASV1,d__Bacteria; p__Proteobacteria; c__Gammaproteobacteria; o__Pseudomonadales; f__Moraxellaceae; g__Psychrobacter,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Corynebacteriales; f__Corynebacteriaceae; g__Corynebacterium|ASV18,d__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Sphingomonadales; f__Sphingomonadaceae; g__Sphingomonas,d__Bacteria; p__Firmicutes; c__Bacilli; o__Bacillales; f__Planococcaceae; g__Rummeliibacillus,d__Bacteria; p__Firmicutes; c__Clostridia; o__Lachnospirales; f__Lachnospiraceae,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Bifidobacteriales; f__Bifidobacteriaceae; g__Gardnerella|ASV2
LAMI.RD001.D0.C1,0.084107,0.034757,0.106925,0.026532,0.005572,0.000531,0.006633,0.106129,0.006368,0.035819,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D14.C1,0.120456,0.120987,0.056779,0.024675,0.003184,0.000000,0.003980,0.035288,0.004776,0.088883,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD004.D0.C2,0.438313,0.025206,0.037410,0.021491,0.003715,0.000000,0.014858,0.006368,0.008490,0.033165,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D0.C2,0.092598,0.057575,0.091802,0.019899,0.004245,0.000531,0.004776,0.107190,0.011940,0.056248,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD011.D0.C2,0.565667,0.077209,0.032369,0.015919,0.005041,0.000000,0.012735,0.048554,0.006898,0.001592,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D14.C2,0.117803,0.054656,0.107986,0.014327,0.006368,0.000000,0.009286,0.106394,0.002653,0.047227,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD004.D28.C2,0.056779,0.004776,0.167418,0.073229,0.004510,0.000000,0.008225,0.010878,0.101353,0.051473,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD017.D14.C2,0.465906,0.168745,0.006898,0.163704,0.003715,0.000000,0.014327,0.006633,0.019369,0.014858,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD011.D14.C1,0.547360,0.265057,0.019103,0.023348,0.014327,0.000000,0.009021,0.008490,0.002388,0.000265,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD004.D0.C1,0.156806,0.012735,0.055983,0.022022,0.003980,0.000000,0.018042,0.000796,0.003715,0.017777,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D28.C1,0.153887,0.121252,0.075882,0.019103,0.009021,0.000265,0.013531,0.023348,0.002919,0.049881,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD017.D28.C1,0.315468,0.071106,0.047493,0.062881,0.321836,0.000000,0.011940,0.010082,0.007960,0.004510,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD011.D14.C2,0.150438,0.029716,0.003715,0.000000,0.036614,0.724065,0.008490,0.000531,0.005837,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD017.D0.C1,0.763067,0.044574,0.020960,0.048023,0.011674,0.001327,0.023083,0.005572,0.006368,0.005306,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD017.D28.C2,0.409392,0.136906,0.016185,0.158928,0.070310,0.000000,0.024675,0.003449,0.010613,0.010082,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD007.D14.C1,0.522420,0.092598,0.034492,0.009552,0.005041,0.002919,0.061820,0.017246,0.025736,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD007.D14.C2,0.393473,0.118599,0.035288,0.016185,0.004776,0.001857,0.074290,0.035023,0.070841,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD017.D0.C2,0.520828,0.081985,0.019899,0.136641,0.004245,0.000531,0.066861,0.024940,0.009552,0.004245,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD018.D0.C1,0.090475,0.002919,0.038472,0.104802,0.125232,0.000000,0.037676,0.003449,0.014327,0.003715,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D28.C2,0.225259,0.130804,0.059698,0.020430,0.002919,0.000265,0.021226,0.021491,0.001327,0.071372,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD018.D0.C2,0.101088,0.011409,0.126824,0.043778,0.145397,0.000000,0.007429,0.015654,0.001592,0.000531,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD007.D28.C1,0.658530,0.036084,0.048023,0.003980,0.002653,0.000000,0.039798,0.022552,0.016715,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD006.D14.C1,0.126293,0.044839,0.012470,0.034227,0.000000,0.000000,0.027594,0.000000,0.059167,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD007.D28.C2,0.451048,0.100557,0.003980,0.003980,0.002388,0.000000,0.132927,0.033961,0.062351,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD006.D14.C2,0.187318,0.093924,0.015123,0.039798,0.004245,0.000531,0.046962,0.001327,0.105864,0.001857,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
v4_metabolomics_path = f'../Data/multi-omics/metabolomics-tbl_16S_V4-ASV-matched_relative_{skin_group}.biom'
biom_to_df(v4_metabolomics_path)

,Heteroaromatic compounds|262,Imidazolyl carboxylic acids and derivatives|1074,N-acyl amines|3496,Alkyl glycosides|12591,Alpha amino acids|18483,Proline and derivatives|954,Benzoic acid esters|18532,Alpha amino acids|1368,Alpha amino acids|20989,N-acyl amines|24184,...,Heteroaromatic compounds|19517,Purine nucleosides|1801,Pyrimidine nucleosides|379,Fatty acid esters|19932,Carboxylic acid esters|21345,Carboxylic acid esters|4863,"Amino acids, peptides, and analogues|1880",Peptides|30669,Acetanilides|5062,Azacyclic compounds|724
LAMI.RD001.D0.C1,0.285327,0.158422,0.024636,0.014872,0.020569,0.049962,0.015229,0.033877,0.014830,0.001087,...,0.000418,0.001634,0.000837,0.000239,0.000216,0.000886,0.000938,0.000303,0.000473,0.000425
LAMI.RD001.D14.C1,0.264331,0.152012,0.007181,0.013366,0.023745,0.046565,0.025691,0.046948,0.012604,0.001806,...,0.000288,0.000523,0.000839,0.000222,0.000473,0.000272,0.000044,0.000281,0.000299,0.000138
LAMI.RD001.D14.C2,0.103366,0.016385,0.043136,0.086066,0.026832,0.028153,0.021157,0.043521,0.015541,0.002684,...,0.000406,0.001130,0.000673,0.000236,0.000314,0.000468,0.000744,0.000625,0.000262,0.000719
LAMI.RD001.D0.C2,0.175500,0.058772,0.052827,0.010852,0.021853,0.050223,0.026258,0.035831,0.016158,0.046207,...,0.000395,0.000205,0.000894,0.000313,0.000250,0.000826,0.000186,0.000278,0.000301,0.000307
LAMI.RD001.D28.C1,0.321537,0.252357,0.003940,0.003851,0.020086,0.053773,0.011561,0.035822,0.010961,0.001187,...,0.000135,0.000139,0.001193,0.000228,0.000236,0.000352,0.000177,0.000190,0.000630,0.000122
LAMI.RD001.D28.C2,0.261657,0.253655,0.004361,0.017129,0.013390,0.058989,0.011516,0.036846,0.005626,0.020389,...,0.000235,0.000192,0.000648,0.000289,0.000150,0.000722,0.000460,0.000169,0.000969,0.000405
LAMI.RD006.D14.C1,0.158336,0.056893,0.278147,0.007698,0.078648,0.031086,0.012464,0.013509,0.042130,0.000705,...,0.000492,0.000495,0.000403,0.000253,0.000287,0.001035,0.000480,0.000317,0.000152,0.000377
LAMI.RD006.D14.C2,0.084203,0.046621,0.282682,0.030194,0.106633,0.030588,0.018491,0.019823,0.049198,0.001066,...,0.004318,0.001043,0.000487,0.000159,0.000177,0.000051,0.000346,0.000328,0.000236,0.000246
LAMI.RD004.D28.C2,0.204849,0.126047,0.010678,0.010707,0.017451,0.026764,0.035032,0.011909,0.007477,0.053177,...,0.000629,0.000109,0.000270,0.001009,0.000433,0.001361,0.000123,0.000310,0.000529,0.000572
LAMI.RD007.D14.C1,0.084140,0.055199,0.011564,0.063705,0.081078,0.025037,0.030112,0.020698,0.042751,0.068567,...,0.001026,0.000352,0.000686,0.002095,0.000884,0.001556,0.000887,0.000523,0.000716,0.000849
LAMI.RD007.D14.C2,0.075394,0.039377,0.008515,0.019506,0.113328,0.017946,0.026798,0.014680,0.039981,0.066510,...,0.000613,0.000678,0.000766,0.000294,0.000476,0.000389,0.001365,0.000238,0.000497,0.000566
LAMI.RD011.D0.C2,0.111476,0.083677,0.029777,0.122909,0.017354,0.017076,0.027519,0.016405,0.009575,0.070491,...,0.000806,0.002551,0.001462,0.000921,0.000658,0.000126,0.001317,0.000528,0.001091,0.001362
LAMI.RD007.D28.C1,0.080956,0.053862,0.009799,0.094819,0.097691,0.022906,0.047942,0.019197,0.049348,0.003346,...,0.000584,0.000273,0.000404,0.001152,0.001267,0.001773,0.001004,0.000654,0.001253,0.001092
LAMI.RD007.D28.C2,0.155795,0.102315,0.007140,0.010552,0.123652,0.027843,0.038117,0.022179,0.061857,0.002413,...,0.000321,0.003045,0.000866,0.000139,0.000342,0.000116,0.000535,0.000646,0.000453,0.000164
LAMI.RD017.D0.C1,0.181591,0.077257,0.009223,0.019040,0.036124,0.055524,0.033717,0.041134,0.012181,0.001899,...,0.000227,0.000311,0.000768,0.001367,0.001373,0.001454,0.000384,0.000525,0.000451,0.001032
LAMI.RD017.D0.C2,0.199055,0.092716,0.008184,0.034201,0.053387,0.055182,0.022857,0.047812,0.014053,0.001189,...,0.000535,0.000345,0.001368,0.001231,0.001029,0.000511,0.001135,0.000366,0.000485,0.000897
LAMI.RD011.D14.C1,0.067254,0.030340,0.207028,0.114228,0.018081,0.020914,0.036701,0.013400,0.008928,0.002487,...,0.000727,0.000939,0.000578,0.000604,0.000950,0.000569,0.000135,0.000752,0.000821,0.000263
LAMI.RD011.D14.C2,0.083728,0.050701,0.126544,0.051913,0.019014,0.019947,0.059338,0.016799,0.009049,0.002985,...,0.003006,0.000239,0.000313,0.000836,0.000690,0.000441,0.000248,0.001839,0.000275,0.000798
LAMI.RD018.D0.C1,0.152722,0.065333,0.006449,0.002362,0.068992,0.035540,0.031240,0.028572,0.025944,0.002783,...,0.000722,0.001730,0.000773,0.001993,0.001692,0.001220,0.000532,0.000774,0.000851,0.000539
LAMI.RD018.D0.C2,0.145783,0.081544,0.009254,0.064335,0.041325,0.014889,0.064890,0.014699,0.019715,0.004188,...,0.001204,0.000527,0.000550,0.001548,0.001560,0.000091,0.000661,0.000928,0.000685,0.000311
LAMI.RD004.D0.C1,0.085938,0.055035,0.040185,0.060419,0.005403,0.027200,0.074933,0.014497,0.003057,0.004000,...,0.000991,0.000305,0.000451,0.000630,0.000745,0.000163,0.000909,0.001289,0.000500,0.000271
LAMI.RD004.D0.C2,0.069091,0.028035,0.008058,0.200307,0.006150,0.016648,0.033873,0.006116,0.003107,0.076989,...,0.000252,0.001167,0.000268,0.000196,0.000407,0.000177,0.000403,0.000610,0.000382,0.000364
LAMI.RD017.D14.C2,0.273727,0.209888,0.021048,0.043814,0.019996,0.057758,0.017623,0.048979,0.002883,0.001123,...,0.000337,0.001000,0.001248,0.000326,0.000247,0.000103,0.000290,0.000265,0.000316,0.000285
LAMI.RD017.D28.C1,0.264308,0.204354,0.005042,0.000961,0.013549,0.049596,0.016485,0.056642,0.006525,0.001551,...,0.000202,0.000595,0.000988,0.000104,0.000461,0.000058,0.000724,0.000333,0.000413,0.000498
LAMI.RD017.D28.C2,0.274789,0.212953,0.002721,0.012480,0.020308,0.054249,0.013040,0.057846,0.010643,0.000656,...,0.000976,0.000219,0.001475,0.000362,0.000303,0.000736,0.000605,0.000214,0.000221,0.000625

In [41]:
v13_asv_path = f'../Data/multi-omics/16S_V1V3-ASV-tbl_metaB-matched_relative_{skin_group}.biom'
biom_to_df(v13_asv_path)

,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Propionibacteriales; f__Propionibacteriaceae; g__Cutibacterium|ASV1,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Corynebacteriales; f__Corynebacteriaceae; g__Lawsonella,d__Bacteria; p__Firmicutes; c__Bacilli; o__Lactobacillales; f__Streptococcaceae; g__Streptococcus|ASV11,d__Bacteria; p__Firmicutes; c__Bacilli; o__Staphylococcales; f__Staphylococcaceae; g__Staphylococcus|ASV8,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Micrococcales; f__Micrococcaceae; g__Micrococcus,d__Bacteria; p__Firmicutes; c__Bacilli; o__Lactobacillales; f__Streptococcaceae; g__Streptococcus|ASV4,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Corynebacteriales; f__Corynebacteriaceae; g__Corynebacterium|ASV6,d__Bacteria; p__Firmicutes; c__Bacilli; o__Lactobacillales; f__Streptococcaceae; g__Streptococcus|ASV6,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Corynebacteriales; f__Corynebacteriaceae; g__Corynebacterium|ASV13,d__Bacteria; p__Firmicutes; c__Negativicutes; o__Veillonellales-Selenomonadales; f__Veillonellaceae; g__Veillonella|ASV3,...,d__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Caulobacterales; f__Caulobacteraceae; g__Caulobacter|ASV1,d__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Caulobacterales; f__Caulobacteraceae; g__Phenylobacterium|ASV5,d__Bacteria; p__Firmicutes; c__Bacilli; o__Lactobacillales; f__Lactobacillaceae; g__Lactobacillus|ASV1,d__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Rhizobiales; f__Beijerinckiaceae; g__Methylobacterium-Methylorubrum,d__Bacteria; p__Actinobacteriota; c__Actinobacteria; o__Propionibacteriales; f__Propionibacteriaceae; g__Cutibacterium|ASV2,d__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Sphingomonadales; f__Sphingomonadaceae; g__Sphingopyxis|ASV2,d__Bacteria; p__Proteobacteria; c__Alphaproteobacteria; o__Caulobacterales; f__Caulobacteraceae; g__Phenylobacterium|ASV3,d__Bacteria; p__Firmicutes; c__Clostridia; o__Lachnospirales; f__Lachnospiraceae; g__Fusicatenibacter,d__Bacteria; p__Firmicutes; c__Clostridia; o__Oscillospirales; f__Ruminococcaceae; g__Ruminococcus,d__Bacteria; p__Acidobacteriota; c__Vicinamibacteria; o__Vicinamibacterales; f__Vicinamibacteraceae; g__Luteitalea
LAMI.RD001.D0.C1,0.624834,0.024144,0.020430,0.022022,0.009817,0.022552,0.015389,0.008225,0.002653,0.008225,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D0.C2,0.472539,0.031839,0.023614,0.041125,0.013797,0.026002,0.026267,0.010613,0.009021,0.009286,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D14.C1,0.576546,0.067127,0.028655,0.021491,0.007960,0.003184,0.055187,0.003449,0.007164,0.004776,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D14.C2,0.461130,0.040064,0.059698,0.036349,0.004245,0.010348,0.043513,0.000531,0.011674,0.018042,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D28.C1,0.624038,0.057575,0.042982,0.030512,0.005837,0.011409,0.031043,0.000000,0.007960,0.008225,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD002.D0.C2,0.767312,0.003449,0.007164,0.030247,0.016185,0.020695,0.000000,0.002388,0.003980,0.000531,...,0.000796,0.000531,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD003.D14.C1,0.874237,0.003715,0.000796,0.022552,0.000000,0.001061,0.000000,0.000000,0.019103,0.000000,...,0.000000,0.000000,0.000265,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD002.D14.C1,0.911117,0.010878,0.006898,0.023879,0.001857,0.004245,0.006368,0.000000,0.003184,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD003.D28.C1,0.628018,0.009552,0.114619,0.025206,0.000000,0.000796,0.000000,0.023083,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD001.D28.C2,0.601751,0.111435,0.016450,0.054126,0.005306,0.003184,0.039798,0.004510,0.006633,0.005306,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD007.D0.C1,0.983550,0.001857,0.000796,0.006102,0.000000,0.002123,0.000000,0.000000,0.000000,0.000531,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD002.D14.C2,0.817724,0.008756,0.003715,0.021756,0.002653,0.006102,0.000000,0.000000,0.008225,0.005837,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD006.D0.C1,0.829663,0.011940,0.002919,0.022287,0.003980,0.000000,0.000000,0.001857,0.007429,0.007429,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD011.D28.C1,0.935792,0.014327,0.004510,0.006633,0.000000,0.000531,0.000000,0.000796,0.002919,0.001061,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD007.D14.C1,0.959671,0.004776,0.000531,0.018042,0.001061,0.000265,0.000000,0.000531,0.004776,0.000265,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD002.D0.C1,0.907137,0.006633,0.004776,0.034757,0.003449,0.000531,0.000000,0.000000,0.001592,0.000265,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD006.D0.C2,0.904484,0.009817,0.000000,0.019634,0.000531,0.000000,0.001061,0.000796,0.011674,0.001327,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD007.D14.C2,0.942956,0.015919,0.001857,0.018042,0.000531,0.002388,0.000000,0.000531,0.006368,0.001327,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD002.D28.C2,0.824887,0.023083,0.000000,0.026532,0.001857,0.000265,0.000531,0.000796,0.000531,0.001327,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD004.D0.C1,0.709472,0.005837,0.010348,0.015919,0.005572,0.024410,0.008490,0.018042,0.005572,0.008490,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD006.D14.C2,0.889095,0.016450,0.000000,0.017777,0.001592,0.000531,0.000000,0.003449,0.011674,0.001061,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD018.D28.C1,0.991775,0.000531,0.000796,0.001061,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD017.D0.C2,0.987530,0.002919,0.000000,0.004776,0.001857,0.000265,0.000000,0.000265,0.000796,0.000265,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD014.D0.C1,0.171398,0.029716,0.141151,0.003980,0.107456,0.048554,0.000000,0.046962,0.006368,0.043513,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD004.D0.C2,0.805784,0.008225,0.002388,0.028124,0.000000,0.007960,0.003449,0.000000,0.000000,0.004245,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD007.D28.C1,0.976386,0.001327,0.000265,0.015654,0.000000,0.000531,0.000000,0.000531,0.002123,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD006.D14.C1,0.701247,0.030247,0.003449,0.013001,0.003980,0.001061,0.000000,0.001857,0.018573,0.000796,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD003.D0.C1,0.525604,0.003980,0.073760,0.000000,0.000000,0.000000,0.000000,0.021756,0.013001,0.012205,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD006.D28.C1,0.835765,0.010613,0.002653,0.017777,0.011940,0.000000,0.000000,0.008756,0.003980,0.000796,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD007.D28.C2,0.973733,0.004776,0.005041,0.007164,0.000000,0.001061,0.000000,0.000000,0.003980,0.000531,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD018.D28.C2,0.993367,0.000000,0.001327,0.002123,0.000000,0.000000,0.000000,0.000000,0.000000,0.000531,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD014.D14.C2,0.824091,0.050942,0.015389,0.009552,0.010878,0.000000,0.000000,0.000000,0.003449,0.003715,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD004.D28.C2,0.448395,0.008490,0.055718,0.004776,0.035288,0.044309,0.012470,0.057044,0.005572,0.002388,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD014.D28.C1,0.471743,0.030247,0.040329,0.008756,0.030777,0.007960,0.000000,0.013266,0.000796,0.029451,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD017.D28.C2,0.996551,0.001061,0.000000,0.000796,0.000796,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD014.D28.C2,0.548156,0.083842,0.024940,0.007429,0.066596,0.001061,0.000000,0.001327,0.012470,0.016715,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD018.D0.C1,0.983815,0.000000,0.000000,0.000265,0.002388,0.000000,0.000265,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD011.D0.C2,0.887238,0.011940,0.002919,0.072698,0.002123,0.001592,0.000265,0.000000,0.002123,0.000265,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD018.D0.C2,0.964181,0.000000,0.003449,0.000531,0.000796,0.002123,0.000000,0.001857,0.000796,0.001592,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD011.D14.C2,0.920934,0.001857,0.000000,0.007960,0.000000,0.000265,0.000000,0.000000,0.000265,0.000265,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
LAMI.RD018.D14.C1,0.975060,0.000000,0.002919,0.001327,0.000000,0.000796,0.000000,0.000000,0.000000,0.000796,...,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
v13_metabolomics_path = f'../Data/multi-omics/metabolomics-tbl_16S_V1V3-ASV-matched_relative_{skin_group}.biom'
biom_to_df(v13_metabolomics_path)

,Heteroaromatic compounds|262,Imidazolyl carboxylic acids and derivatives|1074,N-acyl amines|3496,Alkyl glycosides|12591,Alpha amino acids|18483,Benzoic acid esters|18532,Proline and derivatives|954,Cyanogenic glycosides|12132,Alpha amino acids|1368,Alpha amino acids|20989,...,Alpha amino acids|147,Benzoic acid esters|19425,"Amino acids, peptides, and analogues|1880",Peptides|30669,Pyrimidine nucleosides|379,Fatty acid esters|19932,Acetanilides|5062,Azacyclic compounds|724,Carboxylic acid esters|21345,Carboxylic acid esters|4863
LAMI.RD001.D0.C1,0.285327,0.158422,0.024636,0.014872,0.020569,0.015229,0.049962,0.000395,0.033877,0.014830,...,0.000677,0.000329,0.000938,0.000303,0.000837,0.000239,0.000473,0.000425,0.000216,0.000886
LAMI.RD001.D14.C1,0.264331,0.152012,0.007181,0.013366,0.023745,0.025691,0.046565,0.007009,0.046948,0.012604,...,0.000352,0.000652,0.000044,0.000281,0.000839,0.000222,0.000299,0.000138,0.000473,0.000272
LAMI.RD001.D14.C2,0.103366,0.016385,0.043136,0.086066,0.026832,0.021157,0.028153,0.004781,0.043521,0.015541,...,0.001455,0.000471,0.000744,0.000625,0.000673,0.000236,0.000262,0.000719,0.000314,0.000468
LAMI.RD006.D0.C1,0.142424,0.047630,0.014018,0.013038,0.083336,0.023134,0.045235,0.012699,0.029608,0.030526,...,0.001171,0.000432,0.000107,0.000421,0.000621,0.000767,0.000604,0.000391,0.000407,0.000143
LAMI.RD006.D0.C2,0.197538,0.056702,0.012924,0.090815,0.119229,0.021801,0.039522,0.002285,0.029736,0.040801,...,0.000813,0.000515,0.000525,0.000234,0.000782,0.000407,0.000560,0.000570,0.000398,0.000807
LAMI.RD001.D0.C2,0.175500,0.058772,0.052827,0.010852,0.021853,0.026258,0.050223,0.009463,0.035831,0.016158,...,0.000979,0.001036,0.000186,0.000278,0.000894,0.000313,0.000301,0.000307,0.000250,0.000826
LAMI.RD002.D14.C1,0.140331,0.089981,0.009363,0.009860,0.034549,0.032531,0.023837,0.144408,0.021412,0.014559,...,0.000817,0.000754,0.000783,0.000761,0.001181,0.000346,0.001353,0.000897,0.000657,0.000606
LAMI.RD002.D14.C2,0.131311,0.084073,0.007331,0.281366,0.028459,0.028646,0.026838,0.003576,0.019951,0.012933,...,0.001047,0.000709,0.000587,0.000572,0.000673,0.000104,0.000577,0.000935,0.000567,0.000079
LAMI.RD003.D14.C1,0.058297,0.013318,0.280321,0.021470,0.040792,0.032121,0.015599,0.055775,0.012912,0.021718,...,0.000589,0.000754,0.000372,0.000746,0.000408,0.000266,0.001674,0.000530,0.000671,0.000294
LAMI.RD007.D0.C1,0.044163,0.033863,0.194778,0.025252,0.097776,0.040497,0.024994,0.005142,0.016107,0.063881,...,0.000973,0.000906,0.000838,0.000588,0.000905,0.001823,0.000381,0.000497,0.000687,0.000431
LAMI.RD001.D28.C1,0.321537,0.252357,0.003940,0.003851,0.020086,0.011561,0.053773,0.003133,0.035822,0.010961,...,0.000416,0.000198,0.000177,0.000190,0.001193,0.000228,0.000630,0.000122,0.000236,0.000352
LAMI.RD001.D28.C2,0.261657,0.253655,0.004361,0.017129,0.013390,0.011516,0.058989,0.001564,0.036846,0.005626,...,0.000301,0.000426,0.000460,0.000169,0.000648,0.000289,0.000969,0.000405,0.000150,0.000722
LAMI.RD006.D14.C1,0.158336,0.056893,0.278147,0.007698,0.078648,0.012464,0.031086,0.044938,0.013509,0.042130,...,0.001022,0.000414,0.000480,0.000317,0.000403,0.000253,0.000152,0.000377,0.000287,0.001035
LAMI.RD006.D14.C2,0.084203,0.046621,0.282682,0.030194,0.106633,0.018491,0.030588,0.010978,0.019823,0.049198,...,0.000384,0.000464,0.000346,0.000328,0.000487,0.000159,0.000236,0.000246,0.000177,0.000051
LAMI.RD002.D28.C2,0.035117,0.017512,0.259512,0.129326,0.024960,0.023958,0.014649,0.001937,0.007791,0.010194,...,0.000727,0.001034,0.000697,0.000630,0.000424,0.000989,0.000927,0.000693,0.000129,0.000995
LAMI.RD003.D28.C1,0.080587,0.029795,0.069663,0.029791,0.040003,0.056141,0.038491,0.024752,0.019941,0.025289,...,0.000361,0.001271,0.000609,0.001206,0.000199,0.000558,0.000678,0.000712,0.000676,0.000222
LAMI.RD004.D28.C2,0.204849,0.126047,0.010678,0.010707,0.017451,0.035032,0.026764,0.009357,0.011909,0.007477,...,0.000318,0.001082,0.000123,0.000310,0.000270,0.001009,0.000529,0.000572,0.000433,0.001361
LAMI.RD007.D14.C1,0.084140,0.055199,0.011564,0.063705,0.081078,0.030112,0.025037,0.020068,0.020698,0.042751,...,0.000893,0.001140,0.000887,0.000523,0.000686,0.002095,0.000716,0.000849,0.000884,0.001556
LAMI.RD007.D14.C2,0.075394,0.039377,0.008515,0.019506,0.113328,0.026798,0.017946,0.070216,0.014680,0.039981,...,0.000630,0.001088,0.001365,0.000238,0.000766,0.000294,0.000497,0.000566,0.000476,0.000389
LAMI.RD011.D0.C2,0.111476,0.083677,0.029777,0.122909,0.017354,0.027519,0.017076,0.007549,0.016405,0.009575,...,0.000760,0.001041,0.001317,0.000528,0.001462,0.000921,0.001091,0.001362,0.000658,0.000126
LAMI.RD006.D28.C1,0.022164,0.022397,0.324726,0.030781,0.050057,0.030092,0.017751,0.006627,0.009757,0.019461,...,0.000431,0.000987,0.000547,0.000761,0.000226,0.000219,0.001439,0.000214,0.000068,0.000183
LAMI.RD014.D0.C1,0.052585,0.018129,0.052022,0.009565,0.013605,0.025572,0.012389,0.221124,0.005427,0.006661,...,0.001115,0.001535,0.002073,0.000477,0.000516,0.000211,0.000631,0.000944,0.000699,0.000244
LAMI.RD007.D28.C1,0.080956,0.053862,0.009799,0.094819,0.097691,0.047942,0.022906,0.003244,0.019197,0.049348,...,0.001989,0.001214,0.001004,0.000654,0.000404,0.001152,0.001253,0.001092,0.001267,0.001773
LAMI.RD007.D28.C2,0.155795,0.102315,0.007140,0.010552,0.123652,0.038117,0.027843,0.030823,0.022179,0.061857,...,0.000863,0.000804,0.000535,0.000646,0.000866,0.000139,0.000453,0.000164,0.000342,0.000116
LAMI.RD017.D0.C2,0.199055,0.092716,0.008184,0.034201,0.053387,0.022857,0.055182,0.025321,0.047812,0.014053,...,0.001918,0.000598,0.001135,0.000366,0.001368,0.001231,0.000485,0.000897,0.001029,0.000511
LAMI.RD002.D0.C1,0.229071,0.133063,0.075749,0.022560,0.017226,0.030007,0.035988,0.011458,0.028459,0.010047,...,0.001175,0.000710,0.000512,0.000941,0.000280,0.000706,0.000311,0.000400,0.000327,0.001670
LAMI.RD002.D0.C2,0.205758,0.143891,0.084984,0.036448,0.018336,0.022166,0.031868,0.030802,0.032910,0.009103,...,0.000793,0.000473,0.000709,0.000528,0.000452,0.000359,0.000296,0.000202,0.000561,0.000330
LAMI.RD011.D14.C2,0.083728,0.050701,0.126544,0.051913,0.019014,0.059338,0.019947,0.002386,0.016799,0.009049,...,0.001259,0.001170,0.000248,0.001839,0.000313,0.000836,0.000275,0.000798,0.000690,0.000441
LAMI.RD018.D0.C1,0.152722,0.065333,0.006449,0.002362,0.068992,0.031240,0.035540,0.030664,0.028572,0.025944,...,0.001604,0.000883,0.000532,0.000774,0.000773,0.001993,0.000851,0.000539,0.001692,0.001220
LAMI.RD018.D0.C2,0.145783,0.081544,0.009254,0.064335,0.041325,0.064890,0.014889,0.001716,0.014699,0.019715,...,0.001106,0.001431,0.000661,0.000928,0.000550,0.001548,0.000685,0.000311,0.001560,0.000091
LAMI.RD003.D0.C1,0.040098,0.011611,0.017608,0.065180,0.089102,0.045698,0.019742,0.044727,0.013391,0.051107,...,0.001282,0.000748,0.000598,0.001774,0.000942,0.000550,0.000403,0.000774,0.000430,0.000070
LAMI.RD004.D0.C1,0.085938,0.055035,0.040185,0.060419,0.005403,0.074933,0.027200,0.036606,0.014497,0.003057,...,0.000667,0.001437,0.000909,0.001289,0.000451,0.000630,0.000500,0.000271,0.000745,0.000163
LAMI.RD004.D0.C2,0.069091,0.028035,0.008058,0.200307,0.006150,0.033873,0.016648,0.010335,0.006116,0.003107,...,0.000283,0.001743,0.000403,0.000610,0.000268,0.000196,0.000382,0.000364,0.000407,0.000177
LAMI.RD014.D14.C2,0.126276,0.106785,0.082785,0.053405,0.025523,0.059933,0.024599,0.016778,0.015868,0.015565,...,0.000298,0.001401,0.000226,0.000828,0.000577,0.001146,0.000490,0.000669,0.000493,0.000260
LAMI.RD011.D28.C1,0.089457,0.062009,0.021780,0.010548,0.015042,0.068185,0.014699,0.035342,0.010190,0.006754,...,0.000631,0.002245,0.002820,0.002067,0.000525,0.001331,0.001534,0.001074,0.001410,0.000148
LAMI.RD018.D14.C1,0.155760,0.161114,0.016489,0.004533,0.010387,0.053737,0.022933,0.009330,0.011611,0.006084,...,0.002980,0.001404,0.001755,0.001262,0.000991,0.001453,0.002191,0.001399,0.000676,0.001534
LAMI.RD014.D28.C1,0.084555,0.057040,0.107327,0.032723,0.025923,0.030584,0.011760,0.009016,0.005688,0.016595,...,0.000460,0.000734,0.000704,0.000980,0.000735,0.000452,0.000487,0.000647,0.000363,0.000048
LAMI.RD014.D28.C2,0.092693,0.061414,0.113377,0.038964,0.026203,0.046813,0.011885,0.004296,0.008010,0.014227,...,0.000305,0.001265,0.000480,0.001086,0.000376,0.000362,0.000232,0.000236,0.000340,0.000200
LAMI.RD017.D28.C2,0.274789,0.212953,0.002721,0.012480,0.020308,0.013040,0.054249,0.009623,0.057846,0.010643,...,0.001331,0.000180,0.000605,0.000214,0.001475,0.000362,0.000221,0.000625,0.000303,0.000736
LAMI.RD018.D28.C1,0.271607,0.240139,0.005527,0.001685,0.014399,0.016984,0.028081,0.019348,0.029376,0.006583,...,0.000936,0.000455,0.000099,0.000475,0.000236,0.000115,0.000478,0.000182,0.000252,0.000053
LAMI.RD018.D28.C2,0.304157,0.275046,0.004633,0.030005,0.009977,0.011294,0.028324,0.024678,0.029639,0.004879,...,0.000549,0.000173,0.000360,0.000269,0.000874,0.000219,0.000216,0.000318,0.000429,0.000075