## Explorations

In [1]:
import biom
import pandas as pd

In [2]:
# Function to load BIOM table, sort rows by sum
def biom_to_df(biom_path):

    # Load BIOM table and convert to a DataFrame
    table = biom.load_table(biom_path)

    df = pd.DataFrame(table.matrix_data.toarray(),
                      index=table.ids(axis='observation'),
                      columns=table.ids(axis='sample'))
    
    
    # Sort rows by row sum in descending order
    df['row_sum'] = df.sum(axis=1)
    df = df.sort_values(by='row_sum', ascending=False)
    
    # Drop the 'row_sum' column before proceeding
    df = df.drop(columns=['row_sum'])

    # Transpose df
    df = df.T
    
    return df

In [12]:
metaG_mags_path = '../Data/metaG/Tables/metaG_mags_species.biom'
metaG_mags_df = biom_to_df(metaG_mags_path)
metaG_mags_df

,s__Cutibacterium acnes,s__Malassezia spp.,s__Lawsonella cleavelandensis,s__Corynebacterium spp.,s__Cutibacterium granulosum,s__Actinomyces spp.,s__Alloprevotella spp.,s__Micrococcus luteus,s__Neisseria cerebrosa,s__Streptococcus mitis,s__Marinomonas spp.,s__Porphyromonas pasteri,s__Papillomaviridae,s__Caudoviricetes,s__Psychrobacter spp.,s__Celerinatantimonas spp.,s__Pseudoalteromonas nigrifaciens,s__Psychrobacter celer,s__Papillomaviridae spp.,s__Cirlivirales
LAMI.RD308.D9.C3,0.958221,0.006704,0.001253,0.004631,0.017226,0.004737,0.000291,0.004642,0.000837,9.365683e-04,2.451749e-06,4.427385e-04,1.423596e-06,2.926282e-05,2.372661e-07,5.536208e-07,3.954434e-07,0.000000e+00,0.000000,4.349878e-05
LAMI.RD306.D28.C3,0.686769,0.135709,0.038326,0.044729,0.022959,0.017136,0.000169,0.020260,0.004980,7.691867e-04,9.220619e-06,3.383566e-04,1.945898e-02,7.527366e-03,4.008965e-06,8.017929e-06,9.888779e-06,2.271747e-06,0.000833,3.608068e-06
LAMI.RD310.D16.C2,0.990502,0.005728,0.000167,0.000651,0.002413,0.000181,0.000002,0.000094,0.000080,1.023827e-05,0.000000e+00,5.839012e-05,0.000000e+00,1.119810e-04,0.000000e+00,3.199458e-07,0.000000e+00,0.000000e+00,0.000000,1.439756e-06
LAMI.RD304.D14.C3,0.701787,0.127238,0.035929,0.038021,0.022489,0.028849,0.004151,0.010036,0.009000,1.908478e-02,3.019743e-06,2.669453e-03,2.717769e-05,6.462250e-04,0.000000e+00,2.315136e-05,3.523034e-05,0.000000e+00,0.000000,1.207897e-05
LAMI.RD304.D11.C1,0.988965,0.001060,0.000133,0.000202,0.009299,0.000113,0.000031,0.000093,0.000052,2.503371e-05,0.000000e+00,2.060387e-05,3.090581e-07,3.914736e-06,2.060387e-07,1.030194e-07,1.030194e-07,4.120775e-07,0.000000,1.030194e-07
LAMI.RD306.D14.C3,0.631015,0.145925,0.153908,0.023864,0.009297,0.008990,0.000739,0.004918,0.006744,8.688423e-04,4.311844e-05,1.455392e-03,5.166005e-03,6.918024e-03,4.265604e-05,1.629946e-05,3.595130e-05,3.884127e-05,0.000011,3.467971e-06
LAMI.RD308.D0.C3,0.998569,0.000051,0.000091,0.000251,0.000838,0.000058,0.000002,0.000110,0.000018,5.796213e-06,0.000000e+00,2.857288e-06,0.000000e+00,2.612378e-06,0.000000e+00,8.163680e-08,8.163680e-08,0.000000e+00,0.000000,1.387826e-06
LAMI.RD306.D23.C1,0.945353,0.008211,0.008383,0.023957,0.001704,0.001212,0.000101,0.000778,0.008694,6.165258e-05,0.000000e+00,7.218814e-05,1.749099e-04,1.123208e-03,1.951031e-07,1.268170e-06,6.828608e-07,0.000000e+00,0.000168,3.609407e-06
LAMI.RD308.D23.C2,0.656105,0.016583,0.078321,0.019886,0.002542,0.017165,0.140248,0.007393,0.005395,2.802432e-02,4.351759e-06,2.381550e-02,1.339003e-06,4.490680e-03,2.008504e-06,3.012756e-06,3.682257e-06,0.000000e+00,0.000000,1.908079e-05
LAMI.RD310.D7.C3,0.996010,0.000575,0.000099,0.000509,0.002279,0.000115,0.000000,0.000013,0.000018,3.921212e-07,0.000000e+00,3.646728e-05,3.035018e-04,4.051919e-05,0.000000e+00,0.000000e+00,1.307071e-07,0.000000e+00,0.000000,9.149496e-07
LAMI.RD304.D7.C1,0.941611,0.042842,0.001786,0.005426,0.002762,0.001985,0.000002,0.002586,0.000617,1.346010e-05,7.964555e-07,8.394640e-05,2.725471e-04,8.681364e-06,7.168099e-07,1.752202e-06,1.991139e-06,2.389366e-07,0.000000,8.761010e-07
LAMI.RD308.D11.C2,0.967748,0.008262,0.002228,0.005194,0.010156,0.001417,0.000424,0.003173,0.000501,4.728123e-04,2.746992e-06,3.074434e-04,0.000000e+00,2.164630e-05,5.493984e-07,2.197594e-06,2.197594e-07,1.098797e-07,0.000000,8.845315e-05
LAMI.RD306.D0.C3,0.886814,0.061999,0.024495,0.005111,0.011514,0.004152,0.000011,0.004191,0.000939,1.124188e-04,2.301299e-05,8.146758e-05,2.225123e-04,3.128804e-04,5.212001e-06,4.811077e-07,7.296801e-06,1.924431e-06,0.000005,5.612924e-07
LAMI.RD304.D0.C3,0.956447,0.035858,0.000574,0.002107,0.002739,0.001142,0.000002,0.000538,0.000543,1.558810e-05,0.000000e+00,2.651878e-05,2.946532e-06,1.425741e-06,4.752470e-08,2.043562e-06,2.803958e-06,9.504941e-08,0.000000,4.752470e-08
LAMI.RD304.D28.C3,0.660788,0.174058,0.016278,0.054782,0.035436,0.025327,0.000368,0.021265,0.009673,8.732135e-04,2.336357e-06,9.070907e-04,3.562945e-05,1.296678e-04,2.336357e-06,3.154082e-05,3.329309e-05,5.256804e-06,0.000000,5.840893e-06
LAMI.RD308.D0.C2,0.998993,0.000005,0.000007,0.000017,0.000957,0.000006,0.000003,0.000008,0.000002,3.072690e-06,0.000000e+00,1.229076e-07,2.458152e-07,2.458152e-07,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00
LAMI.RD310.D0.C2,0.917407,0.040385,0.001124,0.013729,0.015793,0.003164,0.000001,0.006699,0.000333,2.408564e-05,1.505353e-07,1.185766e-03,9.182652e-06,1.210304e-04,1.505353e-07,0.000000e+00,1.505353e-07,0.000000e+00,0.000000,2.528993e-05
LAMI.RD306.D11.C1,0.815889,0.032781,0.023156,0.006589,0.004778,0.003113,0.000512,0.003311,0.001369,4.065508e-04,4.827676e-02,2.872706e-04,2.259247e-04,8.643580e-03,2.727131e-02,1.074267e-02,6.498432e-03,5.941138e-03,0.000206,2.527122e-06
LAMI.RD310.D0.C3,0.953686,0.023116,0.001187,0.011664,0.003778,0.002190,0.000000,0.001691,0.000242,1.534862e-05,0.000000e+00,5.967072e-04,1.493067e-03,3.197236e-04,1.180663e-07,5.903317e-07,5.903317e-07,5.903317e-07,0.000000,1.936288e-05
LAMI.RD310.D14.C3,0.771113,0.190594,0.002587,0.018689,0.008260,0.004183,0.000003,0.000898,0.000610,1.571200e-04,0.000000e+00,1.637182e-03,1.649554e-06,1.241702e-03,8.247770e-07,1.649554e-06,4.123885e-07,4.123885e-07,0.000000,2.268137e-05
LAMI.RD306.D14.C1,0.968202,0.007543,0.004056,0.009108,0.001573,0.000861,0.000038,0.000397,0.000540,5.161052e-05,2.345933e-06,1.781970e-04,7.166730e-03,2.794475e-04,3.753492e-07,7.506984e-07,2.064421e-06,2.815119e-07,0.000002,9.383730e-08
LAMI.RD310.D21.C2,0.968617,0.014411,0.000839,0.008186,0.003011,0.002486,0.000000,0.000646,0.000348,3.667750e-05,0.000000e+00,9.441220e-04,6.904000e-07,4.519531e-04,0.000000e+00,1.553400e-06,1.121900e-06,0.000000e+00,0.000000,2.036680e-05
LAMI.RD308.D14.C3,0.986610,0.003099,0.001561,0.003782,0.002644,0.000827,0.000082,0.001101,0.000135,6.282005e-05,3.529216e-07,4.035071e-05,0.000000e+00,4.458576e-05,0.000000e+00,0.000000e+00,1.176405e-07,0.000000e+00,0.000000,1.141113e-05
LAMI.RD304.D0.C1,0.281654,0.601699,0.010219,0.039079,0.019356,0.018435,0.000076,0.020576,0.007038,5.227898e-04,8.351275e-07,9.194753e-04,2.162980e-04,1.377960e-04,9.186402e-06,2.087819e-05,2.922946e-05,2.505382e-06,0.000004,3.340510e-06

In [9]:
wgs_md = pd.read_csv('../Metadata/wgs_simplied_md.tsv', sep='\t')
PP_304_data = wgs_md[wgs_md['subject_ID'] == 'PP_304']
PP_304_data = PP_304_data.sort_values(by='local_lesion_severity')
PP_304_data

,sample_name,day,subject_ID,c_zone,Zone,local_lesion_severity,inflammatory_lesions_face
7,LAMI.RD304.D0.C3,0,PP_304,C3,Non-lesional,0,19
20,LAMI.RD304.D14.C3,14,PP_304,C3,Non-lesional,0,27
12,LAMI.RD304.D28.C3,28,PP_304,C3,Non-lesional,1,15
9,LAMI.RD304.D11.C1,11,PP_304,C1,Lesional,2,0
14,LAMI.RD304.D0.C1,0,PP_304,C1,Lesional,3,19
0,LAMI.RD304.D7.C1,7,PP_304,C1,Lesional,4,25

In [11]:
PP_304_samples = PP_304_data['sample_name'].to_list()
PP_304_samples

['LAMI.RD304.D0.C3',
 'LAMI.RD304.D14.C3',
 'LAMI.RD304.D28.C3',
 'LAMI.RD304.D11.C1',
 'LAMI.RD304.D0.C1',
 'LAMI.RD304.D7.C1']

In [15]:
subset_metaG = metaG_mags_df[metaG_mags_df.index.isin(PP_304_samples)]

# Create a mapping from sample names to their order position
order_mapping = {sample: i for i, sample in enumerate(PP_304_samples)}

# Assign an order column and sort by it, then drop the helper column
ordered_metaG = (subset_metaG
                 .assign(order=subset_metaG.index.map(order_mapping))
                 .sort_values('order')
                 .drop('order', axis=1))
ordered_metaG

,s__Cutibacterium acnes,s__Malassezia spp.,s__Lawsonella cleavelandensis,s__Corynebacterium spp.,s__Cutibacterium granulosum,s__Actinomyces spp.,s__Alloprevotella spp.,s__Micrococcus luteus,s__Neisseria cerebrosa,s__Streptococcus mitis,s__Marinomonas spp.,s__Porphyromonas pasteri,s__Papillomaviridae,s__Caudoviricetes,s__Psychrobacter spp.,s__Celerinatantimonas spp.,s__Pseudoalteromonas nigrifaciens,s__Psychrobacter celer,s__Papillomaviridae spp.,s__Cirlivirales
LAMI.RD304.D0.C3,0.956447,0.035858,0.000574,0.002107,0.002739,0.001142,0.000002,0.000538,0.000543,0.000016,0.000000e+00,0.000027,2.946532e-06,0.000001,4.752470e-08,2.043562e-06,2.803958e-06,9.504941e-08,0.000000,4.752470e-08
LAMI.RD304.D14.C3,0.701787,0.127238,0.035929,0.038021,0.022489,0.028849,0.004151,0.010036,0.009000,0.019085,3.019743e-06,0.002669,2.717769e-05,0.000646,0.000000e+00,2.315136e-05,3.523034e-05,0.000000e+00,0.000000,1.207897e-05
LAMI.RD304.D28.C3,0.660788,0.174058,0.016278,0.054782,0.035436,0.025327,0.000368,0.021265,0.009673,0.000873,2.336357e-06,0.000907,3.562945e-05,0.000130,2.336357e-06,3.154082e-05,3.329309e-05,5.256804e-06,0.000000,5.840893e-06
LAMI.RD304.D11.C1,0.988965,0.001060,0.000133,0.000202,0.009299,0.000113,0.000031,0.000093,0.000052,0.000025,0.000000e+00,0.000021,3.090581e-07,0.000004,2.060387e-07,1.030194e-07,1.030194e-07,4.120775e-07,0.000000,1.030194e-07
LAMI.RD304.D0.C1,0.281654,0.601699,0.010219,0.039079,0.019356,0.018435,0.000076,0.020576,0.007038,0.000523,8.351275e-07,0.000919,2.162980e-04,0.000138,9.186402e-06,2.087819e-05,2.922946e-05,2.505382e-06,0.000004,3.340510e-06
LAMI.RD304.D7.C1,0.941611,0.042842,0.001786,0.005426,0.002762,0.001985,0.000002,0.002586,0.000617,0.000013,7.964555e-07,0.000084,2.725471e-04,0.000009,7.168099e-07,1.752202e-06,1.991139e-06,2.389366e-07,0.000000,8.761010e-07