In [1]:
import pandas as pd
import numpy as np
import biom
from biom import Table
from biom.util import biom_open
from biom import load_table

In [4]:
# Function to load BIOM table, collapse by taxa, sort rows by row sum
def load_biom_table(biom_path):

    # Load BIOM table and convert to a DataFrame
    table = biom.load_table(biom_path)
    df = pd.DataFrame(table.matrix_data.toarray(),
                      index=table.ids(axis='observation'),
                      columns=table.ids(axis='sample'))
    
    return df

In [ ]:
metaB_method2 = load_biom_table('../metabolomics_method2.biom')
metaB_method2

,LAMI.RD001.D0.C1,LAMI.RD308.D2.C2,LAMI.RD304.D11.C1,LAMI.RD304.D11.C2,LAMI.RD304.D0.C1,LAMI.RD304.D0.C2,LAMI.RD001.D14.C1,LAMI.RD304.D0.C3,LAMI.RD001.D14.C2,LAMI.RD006.D0.C1,...,LAMI.RD310.D0.C2,LAMI.RD310.D0.C3,LAMI.RD304.D9.C1,LAMI.RD304.D9.C2,LAMI.RD319.D2.C1,LAMI.RD318.D9.C3,LAMI.RD308.D9.C3,LAMI.RD319.D2.C2,LAMI.RD319.D2.C3,LAMI.RD318.D21.C2
4293,4.770763e+03,4166.871,2342.999,740.01514,725.83435,5084.213,6102.134,0.000,15477.288,5.137698e+03,...,4188.890,3274.6375,2352.2485,5466.2266,0.000,0.000,0.000,1567.8933,0.0000,0.000
15974,0.000000e+00,0.000,0.000,6008.39450,6228.51170,0.000,0.000,0.000,0.000,0.000000e+00,...,17157.180,8754.7850,0.0000,0.0000,0.000,0.000,0.000,0.0000,25945.3710,0.000
2531,7.281270e+04,56668.180,116903.530,69846.52000,75098.50000,178867.020,141313.830,76078.484,137003.560,1.089918e+05,...,56698.500,83862.3900,76001.6000,91359.5700,45993.550,53799.130,30274.117,63744.7970,47938.9100,23423.326
5907,1.022406e+06,322180.030,548906.900,303948.28000,438357.53000,846918.100,644094.440,491530.900,4245851.500,1.708089e+06,...,323473.700,491144.6000,319621.0300,427207.2800,227666.620,458503.400,1192993.400,458884.6200,403263.2800,415341.060
5946,0.000000e+00,0.000,0.000,0.00000,0.00000,0.000,0.000,0.000,24181.441,0.000000e+00,...,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.0000,0.0000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25998,9.886966e+04,366275.560,106990.060,55033.45300,107743.01000,174531.400,87759.940,80892.890,96833.766,8.546535e+04,...,51995.960,210237.8100,160127.3600,28965.0430,43539.740,40761.030,14812.991,100497.2340,13816.3010,82057.580
33060,0.000000e+00,0.000,0.000,1521.32070,0.00000,0.000,0.000,0.000,0.000,0.000000e+00,...,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.0000,9280.9160,0.000
30635,0.000000e+00,0.000,0.000,0.00000,0.00000,0.000,0.000,0.000,0.000,0.000000e+00,...,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.0000,1639.8352,0.000
26562,4.466812e+04,110988.580,66076.950,19372.97700,49133.24000,95173.340,104116.695,38695.656,90356.070,4.329559e+04,...,61393.040,60102.6880,58727.3900,123312.5800,50667.290,15749.498,0.000,0.0000,0.0000,32831.992
28336,8.376185e+03,11684.108,8903.791,8350.32900,10825.29500,7471.549,22818.605,8212.777,19060.340,4.456192e+03,...,16916.867,18855.3630,10425.5200,25366.2090,16235.378,5134.834,0.000,2682.9302,5966.7130,11968.683

In [9]:
metaB_final = load_biom_table('metabolomics_table_final.biom')
metaB_final = metaB_final.T
metaB_final

,14901.LAMI.RD306.D0.C1,14901.LAMI.RD305.D4.C1,14901.LAMI.RD304.D0.C2,14901.LAMI.RD306.D0.C2,14901.LAMI.RD304.D4.C1,14901.LAMI.RD304.D4.C2,14901.LAMI.RD304.D0.C3,14901.LAMI.RD304.D0.C1,14901.LAMI.RD305.D0.C1,14901.LAMI.RD306.D0.C3,...,14901.LAMI.RD319.D23.C1,14901.LAMI.RD319.D28.C3,14901.LAMI.RD319.D23.C2,14901.LAMI.RD018.D28.C1,14901.LAMI.RD319.D2.C1,14901.LAMI.RD318.D9.C3,14901.LAMI.RD318.D21.C2,14901.LAMI.RD319.D2.C2,14901.LAMI.RD319.D2.C3,14901.LAMI.RD308.D9.C3
17896,23004.2380,15393.367,19837.2150,20943.424,19326.5330,20696.318,19116.020,23146.674,20778.375,29221.9920,...,30732.945,18305.9550,24975.688,21442.838,10102.257,14431.6760,17850.795,18662.8710,12816.9260,15928.6670
5240,74700.1500,74713.810,103978.5100,109250.125,86671.8100,112971.195,129741.110,101128.960,101295.620,89735.2800,...,93639.734,141134.5000,138536.190,144213.720,89956.130,140340.8100,184158.600,123067.8600,124541.9500,129774.3900
31854,4757.0520,24498.250,7888.8228,17261.904,5187.0576,9059.234,17430.312,12919.518,16297.066,21700.8240,...,9026.407,6072.6064,0.000,7291.769,0.000,6922.3853,0.000,18370.6300,4383.3687,6445.1924
31138,0.0000,0.000,0.0000,0.000,4815.0930,0.000,0.000,13540.742,0.000,6767.1787,...,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000
30442,7166.1543,28699.477,8936.1460,12730.012,12773.4710,17364.266,25016.053,9555.068,27721.299,22899.2520,...,5338.755,5341.2812,7122.152,0.000,0.000,0.0000,0.000,5694.0684,0.0000,4487.6630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36120,0.0000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.0000,...,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,4497.1670
34141,0.0000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.0000,...,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000
34312,0.0000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.0000,...,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000
29373,0.0000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,3163.3710,...,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000
29327,0.0000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.0000,...,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000